const APP = {};

const REDIS = {};

const KOTAK_NEO = {};

const HS_WEB_SOCKET = {
  CONNECTION_OPEN: "EVENT/HS_WEB_SOCKET/CONNECTION_OPEN",
  CONNECTION_CLOSED: "EVENT/HS_WEB_SOCKET/CONNECTION_CLOSED",
  MESSAGE: "EVENT/HS_WEB_SOCKET/MESSAGE",
  MARKET_FEED: "EVENT/HS_WEB_SOCKET/MARKET_FEED",
  CREDENTIALS_UPDATED: "EVENT/HS_WEB_SOCKET/CREDENTIALS_UPDATED",
};

const HSI_WEB_SOCKET = {
  MESSAGE: "EVENT/HSI_WEB_SOCKET/MESSAGE",
};

module.exports = {
  EVENT: {
    APP,
    REDIS,
    KOTAK_NEO,
    HS_WEB_SOCKET,
    HSI_WEB_SOCKET,
  },
};
