const STRATEGY = {
  LONG_SHORT_SYNTHETIC_FUTURES: "LONG_SHORT_SYNTHETIC_FUTURES",
  OPTION_BUY_SCALPING: "OPTION_BUY_SCALPING",
  LONG_SHORT_SYNTHETIC_FUTURES_50_200: "LONG_SHORT_SYNTHETIC_FUTURES_50_200",
  OPTION_SELL_SCALPING: "OPTION_SELL_SCALPING",
  OPTION_BUY_SCALPING_15_15: "OPTION_BUY_SCALPING_15_15",
  LONG_SHORT_SYNTHETIC_FUTURES_15_MIN: "LONG_SHORT_SYNTHETIC_FUTURES_15_MIN",
  STATUS: {
    INITIATED: "initiated",
    ACTIVE: "active",
    STARTED: "started",
    ENTERED: "entered",
    PAUSED: "paused",
    STOPPED: "stopped",
    EXITED: "exited",
  },
  TREND: {
    UPTREND: "uptrend",
    DOWNTREND: "downtrend",
    SIDEWAYS: "sideways",
  },
};

module.exports = { STRATEGY };
